@startuml
skinparam classBackgroundColor #ADD8E6
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction

title Project Domain Model



class ExecutionTime{
    executionTime
}
class RawMaterial {
    name
    description
    stock
}

class Product {
    name
    stock
    manufacturingDate
}

class Component {
    name
    description
    stock
}

class Machine {
    machine id
    power
}

class Employee {
    name
    NIF
    address
    phoneNumber
    birthdate
    salary
}

class Operation {
    name
    executionTime
    status
    type
}

class Station {
    name
    capacity
    status
    type
}

class Factory {
    name
    specialty
    address
}

class Order {
    orderDate
    deliveryDate
}

class Client {
    name
    NIF
    address
    phoneNumber
}


Component "1..*" -- "1..*" RawMaterial: made of >
Product "1..*" -- "1..*" Component : is made of >
Component "1" -- "1..*" Operation : is related to >
RawMaterial "1" -- "1..*" Operation : is related to >
Product "1" -- "1..*" Operation : is related to >
Order "1" -- "1..*" Operation : has >
'assumindo que não existem encomendas iguais
Client "1" -- "1..*" Order : places >
ExecutionTime "1..*" -- "1..*" Machine : has >
Operation "1..*" -- "1..*" ExecutionTime : has >
Employee "1..*" -- "1..*" Machine : is operated by <
Station "1" -- "1..*" Machine : has >
Factory "1" -- "1..*" Station : has >
Factory "1" -- "1..*" Employee : has >

@enduml
