@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Actor" as Actor
participant ":UserInterface" as UI
participant ":Controller" as CTRL
participant ":RepositoryHandler" as RepoHandler
participant "repositories\n:RepositoryHandler" as RepoPlatform
participant "repository:\nRepositoryClass" as RepositoryClass
participant ":ItemClass" as ItemClass

activate Actor

Actor -> UI : action request
activate UI

UI -> CTRL : create operation

UI --> Actor : asks for input
deactivate UI

Actor -> UI : enters input
activate UI

UI -> CTRL : operation(param)
deactivate UI
activate CTRL

CTRL -> RepoHandler : getInstance()
activate RepoHandler
RepoHandler --> CTRL : repository handler
deactivate RepoHandler

CTRL -> RepoPlatform : getRepository()
activate RepoPlatform
RepoPlatform --> CTRL : repository
deactivate RepoPlatform

CTRL -> RepositoryClass : createItem(param)
deactivate CTRL
activate RepositoryClass

RepositoryClass -> ItemClass : create(param)
deactivate RepositoryClass

activate ItemClass
ItemClass -> ItemClass : validateAttribute(item)
activate ItemClass
ItemClass -> ItemClass : validateOtherRules(item)
activate ItemClass
ItemClass --> ItemClass
deactivate ItemClass
ItemClass --> ItemClass
deactivate ItemClass

ItemClass --> RepositoryClass : item
deactivate ItemClass
activate RepositoryClass

RepositoryClass -> RepositoryClass : checkForDuplicates()
activate RepositoryClass
RepositoryClass --> RepositoryClass
deactivate RepositoryClass
RepositoryClass -> RepositoryClass : addItem(item)
deactivate RepositoryClass

CTRL <-- RepositoryClass : item
deactivate RepositoryClass
activate CTRL

CTRL --> UI : item
deactivate CTRL
activate UI

UI --> Actor : displays success message
deactivate UI
deactivate Actor
@enduml
