@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

class ProductionLine {
    - Map<Integer, LinkedList<Order>> productionLine
    + newOrder(Order order, Integer priority) : void
    + removeOrderFromPL(String orderId) : void
    + searchOrder(String id) : Order
    + getOrdersByPriority(Integer priority) : LinkedList<Order>
    + markOrderAsCompleted(String orderId) : void
}

class Order {
    - String id
    - boolean ready
    - LocalDate deliveryDate
    + getId() : String
    + setReady(boolean ready) : void
    + setDeliveryDate(LocalDate date) : void
}

ProductionLine --> "*" Order : contains
@enduml
