@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Client" as User
participant ":Simulator" as Simulator
participant "WorkstationsPerOperation" as WorkstationsPerOp
participant "List<Workstation>" as WorkstationList
participant "Workstation" as Workstation

User -> Simulator : Request workstation analysis
activate Simulator

Simulator -> WorkstationsPerOp : getWorkstationsAscendingByPercentage()
activate WorkstationsPerOp

WorkstationsPerOp -> WorkstationList : Return sorted list of workstations
deactivate WorkstationsPerOp
activate WorkstationList

Simulator <- WorkstationList : List of workstations in ascending order
deactivate WorkstationList

loop for each workstation
    Simulator -> Workstation : getId(), getExecutiontimeTotal(), getOperationTimeTotal()
    activate Workstation
    Simulator <- Workstation : ID, Execution Time, Operation Time
    deactivate Workstation

    Simulator -> User : Display workstation details (ID, Execution Time, Percentage)
deactivate Simulator
end


@enduml
